version: '1.0.7.{build}'
image: Visual Studio 2019
configuration: Release
before_build:
  - ps: dotnet --version
  - ps: dotnet restore src\TypeProviders.csproj
build_script:
  - ps: dotnet build src\TypeProviders.csproj --configuration Release
test_script:
 - ps: dotnet test --test-adapter-path:. --logger:Appveyor
artifacts:
  - path: src\bin\Release\*.nupkg
    name: Nuget Package
deploy:
  - provider: Environment
    name: Maestria MyGet
    on:
      branch: master
  - provider: Environment
    name: Maestria NuGet
    on:
      APPVEYOR_REPO_TAG: true
