version: '0.0.2.{build}'
image: Visual Studio 2019
configuration: Release
before_build:
  - ps: dotnet --version
  - ps: dotnet restore TypeProviders.sln
build_script:
  - ps: dotnet build TypeProviders.sln
test_script:
  - ps: dotnet test --test-adapter-path:. --logger:Appveyor
artifacts:
  - path: src\Core\bin\Release\*.nupkg
    name: Nuget Package Core
  - path: src\Generators\bin\Release\*.nupkg
    name: Nuget Package Generators
deploy:
  - provider: Environment
    name: Maestria MyGet
    on:
      branch: master
  - provider: Environment
    name: Maestria NuGet
    on:
      APPVEYOR_REPO_TAG: true
