version: '0.0.9.{build}'
image: Visual Studio 2019
configuration: Release
before_build:
  - ps: dotnet --version
  - ps: dotnet restore src\Core\Core.csproj
  - ps: dotnet restore src\Generators\Generators.csproj
build_script:
  - ps: dotnet build src\Core\Core.csproj
  - ps: dotnet build src\Generators\Generators.csproj
#test_script:
#  - ps: dotnet test --test-adapter-path:. --logger:Appveyor
artifacts:
  - path: src\Core\bin\Release\*.nupkg
    name: Nuget Package Core
  - path: src\Generators\bin\Release\*.nupkg
    name: Nuget Package Generators
deploy:
  - provider: Environment
    name: Maestria MyGet
    on:
      branch: master
  - provider: Environment
    name: Maestria NuGet
    on:
      APPVEYOR_REPO_TAG: true
