//----------------------
// <auto-generated>
//     Generated using Maestria.TypeProviders (https://github.com/MaestriaNet/TypeProviders)
// </auto-generated>
//----------------------

using System;

/// <summary>
/// Map excel file and auto generate DTO and Factory classes
/// </summary>
[AttributeUsage(AttributeTargets.Class)]
public class ExcelProviderAttribute : Attribute
{
    public const string TypeFullName = "ExcelProviderAttribute";

    /// <summary>
    ///     <para>
    ///         File path to load Excel template and generate source code.
    ///     </para>
    ///     <para>
    ///         It's supported relative path with format "..\..\folder\file.xlsx".
    ///         The relative path is based at the source code file location.
    ///     </para>
    /// </summary>
    public string TemplatePath { get; set; }

    /// <summary>
    /// Sheet position to build classes. Stated from 1.
    /// </summary>
    public int SheetPosition { get; set; } = 1;

    /// <summary>
    /// Sheet name to build classes.
    /// </summary>
    public string SheetName { get; set; }
}
