using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using ClosedXML.Excel;
using Maestria.Extensions;
using Maestria.FluentCast;
using Maestria.TypeProviders.Common;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace Maestria.TypeProviders.Excel
{
    [Generator]
    public class ExcelGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
/*#if DEBUG
            if (!Debugger.IsAttached)
                Debugger.Launch();
#endif*/
            context.RegisterForSyntaxNotifications(() => new ExcelContextReceiver());
            context.RegisterForPostInitialization(ctx => {
                ctx.AddSource("ExcelProviderAttribute.cs", GeneratorExtensions.GetEmbeddedSourceCode("Maestria.TypeProviders.Excel.ExcelProviderAttribute.cs"));
            });
        }

        public void Execute(GeneratorExecutionContext context)
        {
            if (context.SyntaxContextReceiver is not ExcelContextReceiver receiver)
                return;

            var classSymbols = GetClassSymbols(context, receiver);

            if (classSymbols.Any())
                context.AddSource("ExcelExtensions.cs", GeneratorExtensions.GetEmbeddedSourceCode("Maestria.TypeProviders.Excel.ExcelExtensions.cs"));

            foreach (var classSymbol in classSymbols)
            {
                var name = classSymbol.ToDisplayString();
                try
                {
                    context.AddSource(
                        $"{name}.ExcelTypeProvider.cs",
                        SourceText.From(CreateExcelProvider(classSymbol), Encoding.UTF8));
                }
                catch (Exception e)
                {
                    context.ReportDiagnostic(Diagnostic.Create(DiagnosticErrors.Generic, classSymbol.Locations.First(), classSymbol.Name, e.Message));
                }
            }
        }

        private ExcelProviderAttribute GetExcelProviderAttribute(INamedTypeSymbol symbol)
        {
            var location = symbol.Locations.FirstOrDefault();
            var basePath = string.IsNullOrWhiteSpace(location?.GetLineSpan().Path) ? "" : Path.GetDirectoryName(location.GetLineSpan().Path);

            var attributes = symbol.GetAttributes()
                .Single(x => x.AttributeClass!.ToDisplayString() == ExcelProviderAttribute.TypeFullName)
                .NamedArguments;

            var templatePathAtt = attributes.FirstOrDefault(x => x.Key == nameof(ExcelProviderAttribute.TemplatePath));
            var sheetPositionAtt = attributes.FirstOrDefault(x => x.Key == nameof(ExcelProviderAttribute.SheetPosition));
            var sheetNameAtt = attributes.FirstOrDefault(x => x.Key == nameof(ExcelProviderAttribute.SheetName));

            var templatePath = templatePathAtt.Value.Value.ToString();
            var sheetPosition = sheetPositionAtt.Value.Value.ToInt32Safe();
            var sheetName = sheetNameAtt.Value.Value.ToStringSafe();

            if (!File.Exists(templatePath))
                templatePath = Path.Combine(basePath, templatePath);

            var result = new ExcelProviderAttribute();
            result.TemplatePath = templatePath;
            result.SheetName = sheetName;
            if (sheetPosition.HasValue)
                result.SheetPosition = sheetPosition.Value;
            return result;
        }

        private string CreateExcelProvider(INamedTypeSymbol classSymbol)
        {
            var attribute = GetExcelProviderAttribute(classSymbol);
            if (!File.Exists(attribute.TemplatePath))
                throw new ArgumentException($"Excel template file not found: {attribute.TemplatePath}");

            var namespaceName = classSymbol.ContainingNamespace.ToDisplayString();
            var isGlobalNamespace = namespaceName.IsGlobalNamespace();
            var columns = GetExcelColumns(attribute);

            var source = new StringBuilder($@"//----------------------
// <auto-generated>
//     Generated using Maestria.TypeProviders (https://github.com/MaestriaNet/TypeProviders)
// </auto-generated>
//----------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.IO;
using ClosedXML.Excel;
using Maestria.FluentCast;
using Maestria.TypeProviders.Excel;

{(isGlobalNamespace ? string.Empty : $"namespace {namespaceName}")}
{(isGlobalNamespace ? string.Empty : "{")}
    public partial class {classSymbol.Name}
    {{
");
            foreach (var column in columns)
                source.Append($"        {column.GetSourceCode()}\r\n");

            source.Append(@$"
    }}

    public static partial class {classSymbol.Name}Factory
    {{
        public static IEnumerable<{classSymbol.Name}> Load(Stream input, int sheetPosition = 1)
        {{
            using var workbook = new XLWorkbook(input);
            return Load(workbook, sheetPosition, null);
        }}

        public static IEnumerable<{classSymbol.Name}> Load(Stream input, string sheetName)
        {{
            using var workbook = new XLWorkbook(input);
            return Load(workbook, 0, sheetName);
        }}

        public static IEnumerable<{classSymbol.Name}> Load(string filePath, int sheetPosition = 1)
        {{
            using var workbook = ExcelExtensions.OpenWorkbook(filePath);
            return Load(workbook, sheetPosition, null);
        }}

        public static IEnumerable<{classSymbol.Name}> Load(string filePath, string sheetName)
        {{
            using var workbook = ExcelExtensions.OpenWorkbook(filePath);
            return Load(workbook, 0, sheetName);
        }}

        public static IEnumerable<{classSymbol.Name}> Load(XLWorkbook workbook, int sheetPosition = 1, string sheetName = """")
        {{
            var result = new List<{classSymbol.Name}>();
            var sheet = string.IsNullOrEmpty(sheetName) ? workbook.Worksheet(sheetPosition) : workbook.Worksheet(sheetName);
            foreach (var row in sheet.Rows(2, sheet.RowUsedCount()))
            {{
");
            foreach (var column in columns)
            {
                source.Append($"                var {column.PropertyName.ToCamelCase()}Value = row.Cell(sheet.ColumnByName(\"{column.SourceName}\")).Value;\r\n");
            }

            source.Append(@$"                result.Add(new {classSymbol.Name}
                {{
");
            foreach (var column in columns)
            {
                source.Append($"                    {column.PropertyName} = {column.GetCastSourceCode(column.PropertyName.ToCamelCase() + "Value")},\r\n");
            }
            source.Append("                });\r\n");

            source.Append(@$"            }}
            return result;
        }}
    }}
{(isGlobalNamespace ? string.Empty : "}")}");
            return source.ToString();
        }

        private static IEnumerable<INamedTypeSymbol> GetClassSymbols(GeneratorExecutionContext context, ExcelContextReceiver receiver)
        {
            var compilation = context.Compilation;

            return receiver.CandidateClasses
                .Select(x => compilation
                    .GetSemanticModel(x.SyntaxTree)
                    .GetDeclaredSymbol(x))
                .Where(x => HasAttribute(x, ExcelProviderAttribute.TypeFullName));
        }

        private static bool HasAttribute(ISymbol symbol, string typeFullName) => symbol
            .GetAttributes()
            .Any(x => x.AttributeClass?.ToDisplayString() == typeFullName);

        private static IEnumerable<FieldMapInfo> GetExcelColumns(ExcelProviderAttribute attributes)
        {
            using var workbook = ExcelExtensions.OpenWorkbook(attributes.TemplatePath);
            var sheet = attributes.SheetName.IsNullOrEmpty()
                ? workbook.Worksheet(attributes.SheetPosition)
                : workbook.Worksheet(attributes.SheetName);
            for (var i = 1; i <= sheet.ColumnUsedCount(); i++)
            {
                var headerCell = sheet.Row(1).Cell(i);
                yield return new FieldMapInfo
                {
                    SourceName = headerCell.Value.ToString(),
                    PropertyName = headerCell.Value.ToString().Replace(" ", ""),
                    DataType = GetFieldDataType(sheet, i)
                };
            }
        }

        private static string GetFieldDataType(IXLWorksheet sheet, int columnIndex)
        {
            var rows = sheet.RowsUsed()
                .Where(x =>
                    x.Cell(columnIndex).Value != null &&
                    x.Cell(columnIndex).Value.ToString() != string.Empty)
                .ToImmutableArray();
            if (rows.Length < 2)
                return "object";

            var cell = rows[1].Cell(columnIndex);
            if (cell.DataType == XLDataType.Text)
                return "string";

            var hasNull = sheet.RowsUsed().Any(x =>
                x.Cell(columnIndex).CachedValue == null ||
                x.Cell(columnIndex).CachedValue.ToString() == string.Empty);
            if (cell.DataType == XLDataType.Number)
            {
                var isDecimal = rows.Any(x =>
                    x.Cell(columnIndex).CachedValue != null &&
                    x.Cell(columnIndex).CachedValue.ToInt32Safe() != x.Cell(columnIndex).CachedValue.ToDecimalSafe());

                return (isDecimal ? "decimal" : "int") + (hasNull ? "?" : "");
            }

            var dataType = cell.DataType switch
            {
                XLDataType.Boolean => "bool",
                XLDataType.DateTime => "DateTime",
                XLDataType.TimeSpan => "TimeSpan",
                _ => throw new ArgumentOutOfRangeException(nameof(cell.DataType),
                    $"Not expected excel column data type: {cell.DataType}")
            };
            if (hasNull)
                dataType += "?";
            return dataType;
        }
    }
}